In [15]:
import pandas as pd
movies = pd.read_csv('../movies.csv', sep=',')
ratings = pd.read_csv('../ratings.csv', sep=',')
df = pd.merge(ratings[ratings['rating'] >= 4.0], movies, on='movieId')[['userId', 'title']].groupby('userId').agg({'title':lambda x: list(x)})
ratings_merged = pd.merge(ratings[ratings['rating'] >= 4.0], movies, on='movieId')
basket = pd.crosstab(ratings_merged['userId'], ratings_merged['title']).astype('bool')
basket

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Salem's Lot (2004),'Til There Was You (1997),"'burbs, The (1989)",(500) Days of Summer (2009),*batteries not included (1987),...And Justice for All (1979),00 Schneider - Jagd auf Nihil Baxter (1994),1-900 (06) (1994),...,Zombieland (2009),Zookeeper (2011),Zoolander (2001),Zootopia (2016),Zulu (1964),[REC] (2007),[REC]² (2009),eXistenZ (1999),xXx (2002),¡Three Amigos! (1986)
userId,,,,,,,,,,,,,,,,,,,,,
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
607,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
608,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
609,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
610,True,False,False,False,False,False,False,False,False,False,...,False,False,True,True,False,True,False,False,False,False

In [16]:
basket.shape

(609, 6297)

In [3]:
movies

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
9737,193581,Black Butler: Book of the Atlantic (2017),Action|Animation|Comedy|Fantasy
9738,193583,No Game No Life: Zero (2017),Animation|Comedy|Fantasy
9739,193585,Flint (2017),Drama
9740,193587,Bungo Stray Dogs: Dead Apple (2018),Action|Animation
9741,193609,Andrew Dice Clay: Dice Rules (1991),Comedy

In [4]:
ratings

        userId  movieId  rating   timestamp
0            1        1     4.0   964982703
1            1        3     4.0   964981247
2            1        6     4.0   964982224
3            1       47     5.0   964983815
4            1       50     5.0   964982931
...        ...      ...     ...         ...
100831     610   166534     4.0  1493848402
100832     610   168248     5.0  1493850091
100833     610   168250     5.0  1494273047
100834     610   168252     5.0  1493846352
100835     610   170875     3.0  1493846415

[100836 rows x 4 columns]

In [5]:
df = pd.merge(ratings[ratings['rating'] >= 4.0], movies, on='movieId')[['userId', 'title']].groupby('userId').agg({'title':lambda x: list(x)})

In [6]:
df

                                                    title
userId
1       [Toy Story (1995), Grumpier Old Men (1995), He...
2       [Tommy Boy (1995), Good Will Hunting (1997), G...
3       [Escape from L.A. (1996), Conan the Barbarian ...
4       [Nobody Loves Me (Keiner liebt mich) (1994), F...
5       [Toy Story (1995), Get Shorty (1995), Babe (19...
...                                                   ...
606     [Sense and Sensibility (1995), Four Rooms (199...
607     [Toy Story (1995), Dead Man Walking (1995), Wh...
608     [GoldenEye (1995), Casino (1995), Seven (a.k.a...
609     [GoldenEye (1995), Interview with the Vampire:...
610     [Toy Story (1995), Heat (1995), Casino (1995),...

[609 rows x 1 columns]

In [7]:
ratings_merged = pd.merge(ratings[ratings['rating'] >= 4.0], movies, on='movieId')

In [8]:
basket = pd.crosstab(ratings_merged['userId'], ratings_merged['title']).astype('bool')
basket

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Salem's Lot (2004),'Til There Was You (1997),"'burbs, The (1989)",(500) Days of Summer (2009),*batteries not included (1987),...And Justice for All (1979),00 Schneider - Jagd auf Nihil Baxter (1994),1-900 (06) (1994),...,Zombieland (2009),Zookeeper (2011),Zoolander (2001),Zootopia (2016),Zulu (1964),[REC] (2007),[REC]² (2009),eXistenZ (1999),xXx (2002),¡Three Amigos! (1986)
userId,,,,,,,,,,,,,,,,,,,,,
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
607,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
608,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
609,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
610,True,False,False,False,False,False,False,False,False,False,...,False,False,True,True,False,True,False,False,False,False

In [17]:
from mlxtend.frequent_patterns import fpgrowth
from mlxtend.frequent_patterns import association_rules
frequent_itemsets = fpgrowth(basket, min_support=0.1, use_colnames=True)
frequent_itemsets

      support                                           itemsets
0    0.408867                   frozenset({Forrest Gump (1994)})
1    0.369458      frozenset({Silence of the Lambs, The (1991)})
2    0.364532                    frozenset({Matrix, The (1999)})
3    0.330049  frozenset({Star Wars: Episode IV - A New Hope ...
4    0.293924                     frozenset({Fight Club (1999)})
..        ...                                                ...
858  0.113300  frozenset({Pulp Fiction (1994), Eternal Sunshi...
859  0.108374  frozenset({Shawshank Redemption, The (1994), E...
860  0.106732  frozenset({Forrest Gump (1994), Finding Nemo (...
861  0.101806  frozenset({Pulp Fiction (1994), Trainspotting ...
862  0.106732  frozenset({Kill Bill: Vol. 2 (2004), Kill Bill...

[863 rows x 2 columns]

In [19]:
frequent_itemsets.shape

(863, 2)

In [20]:
rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.5)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,frozenset({Forrest Gump (1994)}),"frozenset({Shawshank Redemption, The (1994)})",0.408867,0.449918,0.275862,0.674699,1.499604,1.0,0.091905,1.690993,0.563591,0.473239,0.408632,0.643919
1,"frozenset({Shawshank Redemption, The (1994)})",frozenset({Forrest Gump (1994)}),0.449918,0.408867,0.275862,0.613139,1.499604,1.0,0.091905,1.528023,0.605650,0.473239,0.345560,0.643919
2,frozenset({Forrest Gump (1994)}),"frozenset({Silence of the Lambs, The (1991)})",0.408867,0.369458,0.210181,0.514056,1.391379,1.0,0.059121,1.297561,0.475846,0.369942,0.229324,0.541473
3,"frozenset({Silence of the Lambs, The (1991)})",frozenset({Forrest Gump (1994)}),0.369458,0.408867,0.210181,0.568889,1.391379,1.0,0.059121,1.371185,0.446106,0.369942,0.270704,0.541473
4,"frozenset({Shawshank Redemption, The (1994)})","frozenset({Silence of the Lambs, The (1991)})",0.449918,0.369458,0.229885,0.510949,1.382968,1.0,0.063659,1.289317,0.503412,0.389972,0.224396,0.566586
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1647,frozenset({Eternal Sunshine of the Spotless Mi...,"frozenset({Shawshank Redemption, The (1994)})",0.172414,0.449918,0.108374,0.628571,1.397080,1.0,0.030802,1.480990,0.343434,0.210863,0.324776,0.434724
1648,frozenset({Finding Nemo (2003)}),frozenset({Forrest Gump (1994)}),0.155993,0.408867,0.106732,0.684211,1.673431,1.0,0.042952,1.871921,0.476803,0.232975,0.465789,0.472627
1649,frozenset({Trainspotting (1996)}),frozenset({Pulp Fiction (1994)}),0.118227,0.400657,0.101806,0.861111,2.149249,1.0,0.054438,4.315271,0.606416,0.244094,0.768265,0.557605
1650,frozenset({Kill Bill: Vol. 2 (2004)}),frozenset({Kill Bill: Vol. 1 (2003)}),0.118227,0.144499,0.106732,0.902778,6.247633,1.0,0.089649,8.799437,0.952557,0.684211,0.886356,0.820707
1651,frozenset({Kill Bill: Vol. 1 (2003)}),frozenset({Kill Bill: Vol. 2 (2004)}),0.144499,0.118227,0.106732,0.738636,6.247633,1.0,0.089649,3.373742,0.981810,0.684211,0.703593,0.820707

In [21]:
rules.shape

(1652, 14)

In [10]:
frequent_itemsets = fpgrowth(basket, min_support=0.1, use_colnames=True)
frequent_itemsets

      support                                           itemsets
0    0.408867                   frozenset({Forrest Gump (1994)})
1    0.369458      frozenset({Silence of the Lambs, The (1991)})
2    0.364532                    frozenset({Matrix, The (1999)})
3    0.330049  frozenset({Star Wars: Episode IV - A New Hope ...
4    0.293924                     frozenset({Fight Club (1999)})
..        ...                                                ...
858  0.113300  frozenset({Eternal Sunshine of the Spotless Mi...
859  0.108374  frozenset({Eternal Sunshine of the Spotless Mi...
860  0.106732  frozenset({Finding Nemo (2003), Forrest Gump (...
861  0.101806  frozenset({Trainspotting (1996), Pulp Fiction ...
862  0.106732  frozenset({Kill Bill: Vol. 1 (2003), Kill Bill...

[863 rows x 2 columns]

In [11]:
frequent_itemsets.shape

(863, 2)

In [12]:
rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.5)

In [13]:
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,frozenset({Forrest Gump (1994)}),"frozenset({Shawshank Redemption, The (1994)})",0.408867,0.449918,0.275862,0.674699,1.499604,1.0,0.091905,1.690993,0.563591,0.473239,0.408632,0.643919
1,"frozenset({Shawshank Redemption, The (1994)})",frozenset({Forrest Gump (1994)}),0.449918,0.408867,0.275862,0.613139,1.499604,1.0,0.091905,1.528023,0.605650,0.473239,0.345560,0.643919
2,"frozenset({Silence of the Lambs, The (1991)})",frozenset({Forrest Gump (1994)}),0.369458,0.408867,0.210181,0.568889,1.391379,1.0,0.059121,1.371185,0.446106,0.369942,0.270704,0.541473
3,frozenset({Forrest Gump (1994)}),"frozenset({Silence of the Lambs, The (1991)})",0.408867,0.369458,0.210181,0.514056,1.391379,1.0,0.059121,1.297561,0.475846,0.369942,0.229324,0.541473
4,"frozenset({Silence of the Lambs, The (1991)})","frozenset({Shawshank Redemption, The (1994)})",0.369458,0.449918,0.229885,0.622222,1.382968,1.0,0.063659,1.456100,0.439174,0.389972,0.313234,0.566586
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1647,frozenset({Eternal Sunshine of the Spotless Mi...,"frozenset({Shawshank Redemption, The (1994)})",0.172414,0.449918,0.108374,0.628571,1.397080,1.0,0.030802,1.480990,0.343434,0.210863,0.324776,0.434724
1648,frozenset({Finding Nemo (2003)}),frozenset({Forrest Gump (1994)}),0.155993,0.408867,0.106732,0.684211,1.673431,1.0,0.042952,1.871921,0.476803,0.232975,0.465789,0.472627
1649,frozenset({Trainspotting (1996)}),frozenset({Pulp Fiction (1994)}),0.118227,0.400657,0.101806,0.861111,2.149249,1.0,0.054438,4.315271,0.606416,0.244094,0.768265,0.557605
1650,frozenset({Kill Bill: Vol. 1 (2003)}),frozenset({Kill Bill: Vol. 2 (2004)}),0.144499,0.118227,0.106732,0.738636,6.247633,1.0,0.089649,3.373742,0.981810,0.684211,0.703593,0.820707
1651,frozenset({Kill Bill: Vol. 2 (2004)}),frozenset({Kill Bill: Vol. 1 (2003)}),0.118227,0.144499,0.106732,0.902778,6.247633,1.0,0.089649,8.799437,0.952557,0.684211,0.886356,0.820707

In [23]:
rules_sorted = rules.sort_values('lift', ascending=False)
rules_sorted[["antecedents", "consequents", "lift"]].head()

,antecedents,consequents,lift
1651,frozenset({Kill Bill: Vol. 1 (2003)}),frozenset({Kill Bill: Vol. 2 (2004)}),6.247633
1650,frozenset({Kill Bill: Vol. 2 (2004)}),frozenset({Kill Bill: Vol. 1 (2003)}),6.247633
1004,frozenset({Star Wars: Episode V - The Empire S...,frozenset({Star Wars: Episode IV - A New Hope ...,4.668042
1000,frozenset({Star Wars: Episode IV - A New Hope ...,frozenset({Star Wars: Episode V - The Empire S...,4.668042
1069,"frozenset({Goodfellas (1990), Godfather, The (...","frozenset({Godfather: Part II, The (1974)})",4.508921

In [21]:
print(rules_sorted[["antecedents", "consequents", "lift"]].head())

                                            antecedents  \
1651              frozenset({Kill Bill: Vol. 2 (2004)})
1650              frozenset({Kill Bill: Vol. 1 (2003)})
1003  frozenset({Star Wars: Episode V - The Empire S...
1000  frozenset({Star Wars: Episode IV - A New Hope ...
1069  frozenset({Goodfellas (1990), Godfather, The (...

                                            consequents      lift
1651              frozenset({Kill Bill: Vol. 1 (2003)})  6.247633
1650              frozenset({Kill Bill: Vol. 2 (2004)})  6.247633
1003  frozenset({Star Wars: Episode IV - A New Hope ...  4.668042
1000  frozenset({Star Wars: Episode V - The Empire S...  4.668042
1069        frozenset({Godfather: Part II, The (1974)})  4.508921

In [16]:
rules_sorted.shape

(1652, 14)

In [17]:
rules.sort_values('lift', ascending=False)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
1651,frozenset({Kill Bill: Vol. 2 (2004)}),frozenset({Kill Bill: Vol. 1 (2003)}),0.118227,0.144499,0.106732,0.902778,6.247633,1.0,0.089649,8.799437,0.952557,0.684211,0.886356,0.820707
1650,frozenset({Kill Bill: Vol. 1 (2003)}),frozenset({Kill Bill: Vol. 2 (2004)}),0.144499,0.118227,0.106732,0.738636,6.247633,1.0,0.089649,3.373742,0.981810,0.684211,0.703593,0.820707
1003,frozenset({Star Wars: Episode V - The Empire S...,frozenset({Star Wars: Episode IV - A New Hope ...,0.174056,0.131363,0.106732,0.613208,4.668042,1.0,0.083868,2.245745,0.951369,0.537190,0.554713,0.712854
1000,frozenset({Star Wars: Episode IV - A New Hope ...,frozenset({Star Wars: Episode V - The Empire S...,0.131363,0.174056,0.106732,0.812500,4.668042,1.0,0.083868,4.405036,0.904610,0.537190,0.772987,0.712854
1069,"frozenset({Goodfellas (1990), Godfather, The (...","frozenset({Godfather: Part II, The (1974)})",0.126437,0.175698,0.100164,0.792208,4.508921,1.0,0.077950,3.966954,0.890854,0.495935,0.747917,0.681151
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
691,frozenset({Jurassic Park (1993)}),"frozenset({Shawshank Redemption, The (1994)})",0.238095,0.449918,0.126437,0.531034,1.180292,1.0,0.019313,1.172969,0.200487,0.225146,0.147463,0.406028
231,frozenset({Star Wars: Episode V - The Empire S...,"frozenset({Shawshank Redemption, The (1994)})",0.275862,0.449918,0.146141,0.529762,1.177464,1.0,0.022026,1.169795,0.208133,0.252125,0.145149,0.427290
921,frozenset({Gladiator (2000)}),"frozenset({Shawshank Redemption, The (1994)})",0.192118,0.449918,0.100164,0.521368,1.158806,1.0,0.013727,1.149279,0.169632,0.184848,0.129889,0.371998
430,frozenset({Raiders of the Lost Ark (Indiana Jo...,"frozenset({Shawshank Redemption, The (1994)})",0.267652,0.449918,0.134647,0.503067,1.118132,1.0,0.014226,1.106955,0.144263,0.230986,0.096621,0.401169
63,frozenset({Star Wars: Episode IV - A New Hope ...,"frozenset({Shawshank Redemption, The (1994)})",0.330049,0.449918,0.165846,0.502488,1.116843,1.0,0.017351,1.105665,0.156159,0.270053,0.095567,0.435550

In [18]:
rules.columns

Index(['antecedents', 'consequents', 'antecedent support',
       'consequent support', 'support', 'confidence', 'lift',
       'representativity', 'leverage', 'conviction', 'zhangs_metric',
       'jaccard', 'certainty', 'kulczynski'],
      dtype='str')

In [22]:
import time
from mlxtend.frequent_patterns import apriori

start_time_fp = time.time()
fp_itemsets = fpgrowth(basket, min_support=0.1, use_colnames=True)
fp_duration = time.time() - start_time_fp

start_time_ap = time.time()
ap_itemsets = apriori(basket, min_support=0.1, use_colnames=True, low_memory=True)
ap_duration = time.time() - start_time_ap

print(f"Время работы FP-Growth: {fp_duration:.4f} секунд")
print(f"Время работы Apriori: {ap_duration:.4f} секунд")

Время работы FP-Growth: 0.0538 секунд
Время работы Apriori: 0.0235 секунд

In [14]:
start_time_fp = time.time()
fp_itemsets = fpgrowth(basket, min_support=0.03, use_colnames=True)
fp_duration = time.time() - start_time_fp

start_time_ap = time.time()
ap_itemsets = apriori(basket, min_support=0.03, use_colnames=True, low_memory=True)
ap_duration = time.time() - start_time_ap

print(f"FP-Growth (support=0.02): {fp_duration:.4f} секунд")
print(f"Apriori (support=0.02): {ap_duration:.4f} секунд")

FP-Growth (support=0.02): 7.6246 секунд
Apriori (support=0.02): 13.9151 секунд